import { query } from './database/db.js';
import crypto from 'crypto';

const sleep = ms => new Promise(r => setTimeout(r, ms));

async function seed() {
  console.log('Seeding Database with Realistic Demo Data...');

  try {
    
    await sleep(2000);

    const resumeId1 = 'res_frontend_dev';
    const resumeId2 = 'res_fullstack_eng';

    await query(`
      INSERT INTO resumes (id, name, candidate_name, skills, experience, summary, education, resume_text, years_of_experience, categories, technologies, status)
      VALUES 
      ($1, 'Frontend Developer Profile', 'Sameer Shaik', 'React, Next.js, Tailwind CSS, TypeScript, GraphQL', '[{"title":"UI Engineer","company":"TechCorp","duration":"2021-Present"}]', 'Passionate frontend developer with 4 years of experience building scalable UIs.', '[{"degree":"B.Tech CS","university":"JNTU","year":"2020"}]', 'Raw resume text...', 4, 'Frontend, UI/UX', 'React, TypeScript, CSS', 'active'),
      ($2, 'Full Stack Engineer', 'Sameer Shaik', 'Node.js, Express, PostgreSQL, React, Docker', '[{"title":"Full Stack Developer","company":"StartupInc","duration":"2020-2023"}]', 'Full stack engineer specialized in MERN stack and cloud infrastructure.', '[{"degree":"B.Tech CS","university":"JNTU","year":"2020"}]', 'Raw resume text...', 5, 'Full Stack, Backend', 'Node.js, React, Docker', 'active')
      ON CONFLICT (id) DO NOTHING;
    `, [resumeId1, resumeId2]);
    console.log('✅ Resumes Seeded');

    const jobId1 = 'job_ui_engineer';
    const jobId2 = 'job_backend_dev';
    const jobId3 = 'job_senior_react';

    await query(`
      INSERT INTO jobs (id, url, title, company, description, skills_required, salary, location, match_score, status)
      VALUES 
      ($1, 'https://linkedin.com/jobs/1234', 'UI Engineer', 'Google', 'Looking for an expert UI engineer for Google Cloud.', 'React, TypeScript, Figma', '$120,000', 'Remote', 92, 'applied'),
      ($2, 'https://wellfound.com/jobs/5678', 'Backend Developer', 'Stripe', 'Node.js backend role focusing on payment APIs.', 'Node.js, PostgreSQL, AWS', '$140,000', 'New York, NY', 88, 'tailoring'),
      ($3, 'https://indeed.com/jobs/9101', 'Senior React Developer', 'Netflix', 'Build the next generation of Netflix web experiences.', 'React, Redux, Performance', '$160,000', 'Los Gatos, CA', 95, 'applied')
      ON CONFLICT (id) DO NOTHING;
    `, [jobId1, jobId2, jobId3]);
    console.log('✅ Jobs Seeded');

    const appId1 = 'app_ui_engineer';
    const appId2 = 'app_senior_react';

    await query(`
      INSERT INTO applications (id, resume_id, job_id, status, score, original_score, ats_score, website, submitted_at, response)
      VALUES 
      ($1, $3, $5, 'success', 92, 85, 96, 'LinkedIn', NOW() - INTERVAL '2 DAYS', 'Application submitted successfully.'),
      ($2, $4, $6, 'success', 95, 88, 98, 'Indeed', NOW() - INTERVAL '1 DAY', 'Application successfully received by ATS.')
      ON CONFLICT (id) DO NOTHING;
    `, [appId1, appId2, resumeId1, resumeId1, jobId1, jobId3]);
    console.log('✅ Applications Seeded');

    await query(`
      INSERT INTO logs (id, application_id, action, message, status, duration)
      VALUES 
      ($1, $2, 'Page Load', 'Navigated to LinkedIn Job Page', 'success', 1200),
      ($3, $2, 'Form Fill', 'Filled personal details and uploaded tailored resume', 'success', 3400),
      ($4, $2, 'Submit', 'Clicked submit application button', 'success', 800)
      ON CONFLICT (id) DO NOTHING;
    `, [crypto.randomBytes(8).toString('hex'), appId1, crypto.randomBytes(8).toString('hex'), crypto.randomBytes(8).toString('hex')]);

    await query(`
      INSERT INTO logs (id, application_id, action, message, status, duration)
      VALUES 
      ($1, $2, 'Page Load', 'Navigated to Indeed Job Page', 'success', 1500),
      ($3, $2, 'Form Fill', 'Filled custom cover letter generated by AI', 'success', 4200),
      ($4, $2, 'Submit', 'Application successfully submitted', 'success', 900)
      ON CONFLICT (id) DO NOTHING;
    `, [crypto.randomBytes(8).toString('hex'), appId2, crypto.randomBytes(8).toString('hex'), crypto.randomBytes(8).toString('hex')]);
    console.log('✅ Logs Seeded');

    await query(`
      INSERT INTO activity_logs (id, action, message, entity_type, entity_id, status)
      VALUES 
      ($1, 'application_submitted', 'Successfully applied for UI Engineer at Google', 'application', $2, 'success'),
      ($3, 'application_submitted', 'Successfully applied for Senior React Developer at Netflix', 'application', $4, 'success'),
      ($5, 'resume_tailored', 'AI successfully tailored profile for Stripe backend role', 'job', $6, 'success'),
      ($7, 'job_imported', 'Imported Backend Developer from Wellfound', 'job', $6, 'info')
      ON CONFLICT (id) DO NOTHING;
    `, [
      crypto.randomBytes(8).toString('hex'), appId1, 
      crypto.randomBytes(8).toString('hex'), appId2, 
      crypto.randomBytes(8).toString('hex'), jobId2,
      crypto.randomBytes(8).toString('hex')
    ]);
    console.log('✅ Activity Logs Seeded');

    console.log('🎉 Seeding Complete! Enjoy your realistic demo data.');
    process.exit(0);
  } catch (err) {
    console.error('Seeding Error:', err);
    process.exit(1);
  }
}

seed();
